function Ydash = TrPredict(X, svmmodels, beta)
% input:
% X: n*m features matrix for prediction, where n is the number of samples, and m is
% the dimension of features
% svmmodel: model generated by DuTrAdaBoostTrain
% beta: parameter generated by DuTrAdaBoostTrain
% output:
% Ydash: n*1 label vector

    N = length(svmmodels);
    start = ceil(N/2);
    l = size(X,1);
    yOne = ones(l,1);
    yTwo = ones(l,1);
    Ydash = ones(l,1);
    for i = start:N
        predict = svmpredict(yOne,X,svmmodels{i});
        %predict = predict == 1;
        yOne = yOne.*((beta(i)*ones(l,1)).^(-predict));
        yTwo = yTwo.*((beta(i)*ones(l,1)).^(-0.5));
    end
    Ydash(yOne < yTwo) = -1;
end
